/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIME_H_RPCGEN
#define _TIME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TIMEPROG 0x20000001
#define PRINTIMEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINTIME 1
extern  char ** printime_1(char **, CLIENT *);
extern  char ** printime_1_svc(char **, struct svc_req *);
extern int timeprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINTIME 1
extern  char ** printime_1();
extern  char ** printime_1_svc();
extern int timeprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIME_H_RPCGEN */
