#!/bin/bash
find -L . -name "*.h" -o -name "*.c" -o -name "*.cpp" -o -name "*.java" > cscope.files
#find . -name "*.h" -o -name "*.c" -o -name "*.cpp" > cscope.files
cscope -bkq -i cscope.files
ctags -R
